apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: ingress-internal-tls
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name}}
    meta.helm.sh/release-namespace: {{ .Release.Namespace}}
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  tls.crt: {{ .Values.global.ingressCerts.internal.crt}}
  tls.key: {{ .Values.global.ingressCerts.internal.key}}
